/**
 * export all action types
 */

export const INITIATE_CONVERSATION = 'INITIATE_CONVERSATION';
export const END_CONVERSATION = 'END_CONVERSATION';
export const CHANGE_CONVERSATION = 'CHANGE_CONVERSATION';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const DELETE_MESSAGE = 'DELELTE_MESSAGE';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const LIKE_MESSAGE = 'LIKE_MESSAGE';
export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const GET_USERS = 'GET_USERS';
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT';
export const SET_ACTIVE_CONVERSATIONS = 'SET_ACTIVE_CONVERSATIONS';